// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqmvBjaSdWo70kxjWybBmvDga_-69zBIQ',
    appId: '1:978457901082:web:ddd5aca79c289590bdb9a3',
    messagingSenderId: '978457901082',
    projectId: 'crudtutorial-d9832',
    authDomain: 'crudtutorial-d9832.firebaseapp.com',
    storageBucket: 'crudtutorial-d9832.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3FVL98VNhhv3SButTi4cQL4MW0sYtNM',
    appId: '1:978457901082:android:ee467434f2dcab5bbdb9a3',
    messagingSenderId: '978457901082',
    projectId: 'crudtutorial-d9832',
    storageBucket: 'crudtutorial-d9832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu4_Zx6vVL8_4WPZdUaLOKCJDIjZcwe04',
    appId: '1:978457901082:ios:dc6b061da27bf4e8bdb9a3',
    messagingSenderId: '978457901082',
    projectId: 'crudtutorial-d9832',
    storageBucket: 'crudtutorial-d9832.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu4_Zx6vVL8_4WPZdUaLOKCJDIjZcwe04',
    appId: '1:978457901082:ios:fd73dfc5f3ef4067bdb9a3',
    messagingSenderId: '978457901082',
    projectId: 'crudtutorial-d9832',
    storageBucket: 'crudtutorial-d9832.appspot.com',
    iosBundleId: 'com.example.crudFlutter.RunnerTests',
  );
}
